spring:
  application:
    name: saml-oauth-example
  main:
    allow-bean-definition-overriding: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      static-locations: classpath:/static/
  security:
    saml2:
      relyingparty:
        registration:
          okta-saml:
            identityprovider:
              entity-id: entity-id
              verification.credentials:
                  - certificate-location: "classpath:saml-certificate/okta.crt"
              singlesignon.url: singlesignon-url
              singlesignon.sign-request: false

server:
  port: 7001
